### ISSUE TITLE
記事編集画面が開けない

### ISSUE THREAD

**Issue by mt8** [inc2734/snow-monkey-editor#104]
以下環境の複数サイトで発生しています。

WordPress 6.2.2
PHP 8.0
snow-monkey-editor 9.2.2

エラーメッセージ

```
Warning: Undefined property: WP_Post_Type::$capabilities in /var/www/html/wp-includes/post.php on line 1869 Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /var/www/html/wp-includes/post.php:1869 Stack trace: 
  #0 /var/www/html/wp-includes/post.php(1869): array_merge(Array, NULL) 
  #1 /var/www/html/wp-content/plugins/snow-monkey-editor/App/Setup/CurrentUser.php(26): get_post_type_capabilities(Object(WP_Post_Type)) 
  #2 /var/www/html/wp-includes/class-wp-hook.php(308): Snow_Monkey\Plugin\Editor\App\Setup\CurrentUser->_wp_enqueue_scripts('') 
  #3 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) 
  #4 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
  #5 /var/www/html/wp-admin/edit-form-blocks.php(272): do_action('enqueue_block_e...') #6 /var/www/html/wp-admin/post.php(187): require('/var/www/html/w...') #7 {main} thrown in /var/www/html/wp-includes/post.php on line 1869
```

こちらでもデバッグしてみますがご報告まで

**Comment by mt8** [comment]
@inc2734 おっと、ちょうど `9.2.3`がリリースされていましたね。こちら解消されておりましたのでCloseします

**Comment by inc2734** [comment]
わーすみません、ご報告ありがとうございます！
